SELECT * FROM CATEGORY;
SELECT * FROM COMMENTS;
SELECT * FROM FRIENDS;
SELECT * FROM OWNER;
SELECT * FROM PETS;
SELECT * FROM POST;
SELECT * FROM PROFILE;


SELECT * FROM OWNER WHERE id_owner = 1;  
SELECT * FROM OWNER WHERE city = 'Madrid'; 
SELECT * FROM PETS WHERE id_pet = 1; 
SELECT * FROM CATEGORY WHERE id_category = 1; 
SELECT * FROM PROFILE WHERE id_pet = 1; 
SELECT * FROM PROFILE WHERE id_owner = 1;  






